---
# tasks file for adepdev-ansible-role-common
#
# Base server packages
# Many are listed because it's unclear what will be installed with vagrant
#
- name: Install system packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - wget
    - nano
    - curl
    - rsync
    - vim
    - git
    - git-lfs
    - zip
    - python-apt
    - python3-apt
    - python3
    - python3-pymysql
    - python-pymysql

- name: Install python(3)-pip
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip
    - python-pip
    - pymysql

- name: Set Timezone to America/New_York
  timezone:
    name: America/New_York
