---
# tasks file for adepdev-ansible-role-common
#
# Base server packages
# Many are listed because it's unclear what will be installed with vagrant
#
- name: Install system packages
  package:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - wget
    - nano
    - curl
    - rsync
    - vim
    - git
    - git-lfs
    - zip

- name: Set Timezone to America/New_York
  timezone:
    name: America/New_York
