---
# tasks file for adepdev-ansible-role-common
#
# Base server packages
# Many are listed because it's unclear what will be installed with vagrant
#
- name: Install system packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - wget
    - nano
    - curl
    - rsync
    - vim
    - git
    - git-lfs
    - zip
    - python3

- name: Run Debian / Ubuntu specific install options
  include:  debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Set Timezone to America/New_York
  timezone:
    name: America/New_York
