---
# tasks file for adepdev-ansible-role-common
#
# Base server packages
# Many are listed because it's unclear what will be installed with vagrant
#
- name: Install system packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - wget
    - nano
    - curl
    - rsync
    - vim
    - git
    - git-lfs
    - zip
    - python-apt
    - python3-apt
    - python3
    - python3-pip
    - python3-pymysql
    - python-pip
    - python-pymysql

- name: Install MYSQL pip dependancies
  command: pip3 install pymysql

- name: Set Timezone to America/New_York
  timezone:
    name: America/New_York
